<div class="shellpea-common-global">
    <div class="shellpea-portfolio">
        <div class="shellpea-portfolio-title">
            <h2>Фотогалерея</h2>
        </div>
        <div class="shellpea-portfolio-content shellpea-clearfix">
            <div class="shellpea-portfolio-content-item">
                <div class="shellpea-img_crop-around">
                    <img src="<?php echo $this->getViewFileUrl('images/img-portfolio01.jpg'); ?>" alt="">
                </div>
            </div>
            <div class="shellpea-portfolio-content-item">
                <div class="shellpea-img_crop-around">
                    <img src="<?php echo $this->getViewFileUrl('images/img-portfolio02.jpg'); ?>" alt="">
                </div>
            </div>
            <div class="shellpea-portfolio-content-item">
                <div class="shellpea-img_crop-around">
                    <img src="<?php echo $this->getViewFileUrl('images/img-portfolio03.jpg'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</div>